import { zodResolver } from "@hookform/resolvers/zod";
import NumberField from "core/ui/fields/NumberField";
import TextField from "core/ui/fields/TextField";
import Button from "core/ui/primitives/Button";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
